_default:
    just --list

@test:
    gleam test --target javascript

@build:
    gleam build --target javascript

@lint:
    gleam run -m glinter

@docs:
    gleam docs build

@docs-open: docs
    open build/dev/docs/take_promise/index.html
